### ISSUE TITLE
Change workedexample directive to support multiple tags

### ISSUE THREAD

**Issue by yolile** [open-contracting/sphinxcontrib-opencontracting#25]
Right now the directive allows only one tag per worked example, however, there are some worked examples that contain more than one topic, for example, "Awards and Contracts" https://standard.open-contracting.org/latest/en/guidance/map/awards_contracts/ and https://standard.open-contracting.org/latest/en/guidance/map/buyers_suppliers/. We could change the directive to allow defining multiple tags separated by commas

**Comment by jpmckinney** [comment]
Sounds good!
